### ISSUE TITLE
Signature Pattern Update for seeEnemyInfo  and radarHax

### ISSUE THREAD

**Issue by steel4me** [0TheSpy/SpyExternal1337hax#6]
I tried to find it with ida, i was not able. Can you give me a hint what i have to search for?

```
radarHax = client_dll + SpyPatternScan(clientBytes, client_dll_size, AY_OBFUSCATE("80 B9 ? ? ? ? ? 74 12 8B 41 08")) + 6; $$$;
seeEnemyInfo = client_dll + 5 + SpyPatternScan(clientBytes, client_dll_size, AY_OBFUSCATE("E8 ? ? ? ? 3B C6 5E 5F")); $$$;
```

**Comment by 0TheSpy** [comment]
Hello. Those signatures are up-to-date and "Overhead Info & Radarhack" feature is working fine.
I personally don't use IDA, I use Cheat Engine instead

![New Bitmap Image (2)](https://user-images.githubusercontent.com/16876342/103438394-e1381180-4c43-11eb-8ee2-010bd43ae3ab.jpg)

**Comment by steel4me** [comment]
Ohhh, you are right, my mistake. Im sorry, interesting part is uprising when signature will change after some update. 
I use IDA or CE rarely ;)
